// Code generated by "stringer -type=ContextSuffix"; DO NOT EDIT.

package parts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NO_SUFFIX-0]
	_ = x[WORD_END-1]
	_ = x[SYL_END-2]
}

const _ContextSuffix_name = "NO_SUFFIXWORD_ENDSYL_END"

var _ContextSuffix_index = [...]uint8{0, 9, 17, 24}

func (i ContextSuffix) String() string {
	if i < 0 || i >= ContextSuffix(len(_ContextSuffix_index)-1) {
		return "ContextSuffix(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContextSuffix_name[_ContextSuffix_index[i]:_ContextSuffix_index[i+1]]
}
