// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package tok

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-1]
	_ = x[ILLEGAL-2]
	_ = x[LPAREN-3]
	_ = x[RPAREN-4]
	_ = x[LBRACKET-5]
	_ = x[RBRACKET-6]
	_ = x[LCURLY-7]
	_ = x[RCURLY-8]
	_ = x[COMMA-9]
	_ = x[STAR-10]
	_ = x[COLON-11]
	_ = x[LINE_ENDING-12]
	_ = x[NUMBER-13]
	_ = x[EQ-14]
	_ = x[DOLLAR-15]
	_ = x[RAW-16]
	_ = x[ARROW-17]
	_ = x[SLASH-18]
	_ = x[DOUBLESLASH-19]
	_ = x[SYLLABLE-20]
	_ = x[LETTERS-21]
	_ = x[REJECT-22]
	_ = x[REPLACE-23]
}

const _TokenType_name = "EOFILLEGALLPARENRPARENLBRACKETRBRACKETLCURLYRCURLYCOMMASTARCOLONLINE_ENDINGNUMBEREQDOLLARRAWARROWSLASHDOUBLESLASHSYLLABLELETTERSREJECTREPLACE"

var _TokenType_index = [...]uint8{0, 3, 10, 16, 22, 30, 38, 44, 50, 55, 59, 64, 75, 81, 83, 89, 92, 97, 102, 113, 121, 128, 134, 141}

func (i TokenType) String() string {
	i -= 1
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
